# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcfoverparRcppClean <- function(y_, z_, x_con_, x_mod_, x_mod_est_, x_con_info_list, x_mod_info_list, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_name_, status_interval = 100L, RJ = FALSE, prior_sample = FALSE, trt_init = 1.0) {
    .Call('_bcf_bcfoverparRcppClean', PACKAGE = 'bcf', y_, z_, x_con_, x_mod_, x_mod_est_, x_con_info_list, x_mod_info_list, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_name_, status_interval, RJ, prior_sample, trt_init)
}

